### ISSUE TITLE
Plugin does't report absense of href attribute and empty href attributes

### ISSUE THREAD

**Issue by gautamz07** [DavidAnson/check-pages#4]
Basically the following fails:

`<a href="#"></a>`

but the following passes:

`<a></a>`

also ,

`<a href=""></a>`

why ? 

If the support for the above 2 are also added , it would be of great help , as currently i have a requirement of testing for all 3 scenarios above. 

Thank you.

**Comment by DavidAnson** [comment]
I'm not sure what options you're using, but I can provide some background. The first example will trigger the `noEmptyFragments` rule because it's exactly the scenario that rule detects (fragment is present but empty). The second example isn't recognized as a link at all (code looks for a+href, img+src, etc.). The third is recognized as a link, but has no fragment, so won't trigger `noEmptyFragments`. Because it points to the current page, it's valid by definition.

Hope this helps!

**Comment by gautamz07** [comment]
@DavidAnson quite insightful , thanks . would still be great if my use case could be accomodated simply because <a href=""></a> and <a></a> is often intended to be <a href="#"></a> , its hard to be meticulous and type out  <a href="#"></a> :) , but ofcourse as you've pointed out going by the definition , the plugins right in ignorning my other 2 use cases ! .. but i'd still love if a feature could be added.

Thanks for your time.

**Comment by DavidAnson** [comment]
I've captured your request in #5, so am closing this issue as we agree things are working correctly. Thanks!
