### ISSUE TITLE
Better reporting

### ISSUE THREAD

**Issue by lukasoppermann** [DavidAnson/check-pages#9]
Hey,

I really like this package. However, it would be nice if you could have a better reporting, my idea:

1. I am always getting the following:

```
[09:46:05] 'checkLinks' errored after 701 ms
[09:46:05] Error: 56 issues.
at /Users/lukasoppermann/Code/veare/node_modules/check-pages/checkPages.js:426:13
    at next (/Users/lukasoppermann/Code/veare/node_modules/check-pages/checkPages.js:435:5)
    at Request.<anonymous> (/Users/lukasoppermann/Code/veare/node_modules/check-pages/checkPages.js:152:11)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/Users/lukasoppermann/Code/veare/node_modules/request/request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
```

In case this is NOT an error in my code, I would think this should not be shown. Does this show up because the package found code errors?

2. Instead of just showing the output, it would be nice to have indicators (e.g. red and green):

❌  http://localhost:8080/portfolio
> Missing Content-Encoding header in response

✅  http://localhost:8080/contact

Currently it is a little hard to get an easy overview of which pages need work and which are fine.

Thanks.

**Comment by DavidAnson** [comment]
Glad you like it!

To your first point, `check-pages` is a library, so logging and error handling are generally up to whatever code is using it. The API allows you to pass `console` as the `Host` parameter for easy logging (https://github.com/DavidAnson/check-pages/blob/master/README.md#host), but you can pass something else that customizes the output if you'd like (such as by coloring it or adding pretty icons). Regarding the exception you are getting, I think that check pages handles it's own errors properly, but if you have a simple demonstration of the problem, I'd like to understand if this is actually a bug in my code.

Regarding your second point, colorization and summarization of output is something that the check-pages-cli package (https://github.com/DavidAnson/check-pages-cli) already supports. If that's relevant to your scenario, please try it out because you may find it's easier to use and maybe more friendly. :)

**Comment by DavidAnson** [comment]
Assuming the above reply was helpful, I'm closing this issue to clean up. Thanks!

**Comment by lukasoppermann** [comment]
Hey @DavidAnson, thank you for your answer. The `cli` is a little inconvenient as I am using it in gulp, however, I just use the logging function from there and it is perfect. For anybody who needs it:

```js
  let host = {
    "log": function log (msg) {
      console.log(chalk.green('✔ ' +msg));
    },
    "error": function error (msg) {
      console.error(chalk.red('× ' +msg));
    }
  };

  checkPages(host, options, callback)
```

I believe the issues arise from redirects on my side, the page errors did not show up before I used your function. So I will investigate this further.
